### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by stefanroellin** [ondras/cyp#12]
In the Library view, if I select a directory and after that click on the button ">>", select a subdirectory and press "Play", then not only the selected subdirectory is added to the queue, but all directories on the same level as the selected subdirectory, i.e. the first selected directory.

I would expect that only the last selected directory is added to the queue in this case.

**Comment by ondras** [comment]
Sounds like a bug then!

**Comment by ondras** [comment]
I don't seem to be able to reproduce the behavior. Weird! Just tried with many directories and it always worked as expected.

Can you provide some more info, please?

  1. are you using the latest version of CYP?
  1. what version of MPD do you use?
  1. does this happen only for the `Play` action, or also for `Enqueue` ?
  1. does this happen for any directory, or only for a particular one?
  1. does this happen at any depth of the filesystem view?

To clarify the last question: say your MPD music directory layout is:
```
- A
  - A.1
    - A.1.1
    - A.1.2
  - A.2
- B
```

I understand that Playing `A.1` also enqueues `A.2`. What happens if you clear the queue and try to play `A.1.1`? Does `A.1.2` get enqueued as well?

**Comment by stefanroellin** [comment]
Strange - I can always reproduce it. I have just checked with the docker container and got the same result.
1. yes, I use the latest version of CYP
2. I have tested with two different versions: 0.21.5 & 0.21.13 - both show the same behavior
3. It happens both for the `Play` and `Enqueue` action
4. All directories are affected
5. This happens everywhere in the filesystem view

Maybe I have to once again try to explain what I did:

1. Click on `Library`
2. Click on `Files and directories`
3. Select a directory A, i.e. it becomes blue (dependent on the setting)
4. While the directory A is blue, click on `>>`
5. In the directory, either click on another directory B (or a file C) - it becomes blue
6. Click either on `Play` or `Enqueue`

Result: not only all files in directory B (and subdirectories)  are added, but all files contained in any subdirectory of A. Or: not only file C is added, but all files, which have directory A as parent.

And interestingly, the files in directory B are added twice to the queue.

I have also tested with Chrome, Chromium and Firefox, which show all the same behavior.

**Comment by ondras** [comment]
>     3\. Select a directory A, i.e. it becomes blue (dependent on the setting)

Ha! This might be the crucial point. I did not consider this step before; I always only clicked `>>` to enter the directory.
In retrospect, it makes perfect sense: the `A` probably remains selected as well, so when you enqueue `A/B`, you really enqueue *all selected items* -- both `A` and `A/B`.

Thanks for this thorough examination! I think I know where to look now.

**Comment by ondras** [comment]
@stefanroellin please try updating to latest CYP. The issue shall be fixed.

**Comment by stefanroellin** [comment]
Thanks for the fix, which works for me.

And thanks for the great software as well!

**Comment by ondras** [comment]
Awesome! :+1:
