### ISSUE TITLE
How to specify password for MPD server?

### ISSUE THREAD

**Issue by emu42** [ondras/cyp#18]
Hello,

I cannot seem to find documentation on how to setup the connection to my mpd server. It is running on the same host as cyp on the default port, but it is configured to require password authentication.

**Comment by ondras** [comment]
Hi,

there is no such feature! Until today, I had no idea that a password protection was available in MPD. I will try to implement that for you.

**Comment by emu42** [comment]
> 
> 
> Hi,
> 
> there is no such feature! Until today, I had no idea that a password protection was available in MPD. I will try to implement that for you.

oh, thank you! :)

**Comment by ondras** [comment]
Non-default server address is currently specified using the `server` query string argument. This is not a nice place for password, because it is a part of the URL and is thus freely visible in the browser's address bar.

The approach above has been chosen so that one CYP instance can be used to control multiple MPDs. This does not seem to be reasonably possible with password-based connections.

One solution would be to specify MPD connection details when running the CYP server process (limiting the web client's ability to override the address). Other solution might be a list of address-password pairings available for CYPs configuration: user selects the address, CYP fills in the password based on a list. What is your opinion here, @emu42 ?

**Comment by emu42** [comment]
For me personally, having just one preconfigured MPD server with a password would suffice. But for CYP it would be a shame to lose the option to control multiple instances, so I agree with your idea of address-password pairings. I assume you would put them in some JSON config file on the server and there should be no need for the browser to ever see the password at all. You could still just select the server via the "server" argument and CYP just matches that to the pairings and applies the password if there is one. But when you say the "user selects the address" I assume you mean some drop-down which would of course be neater. 

In either case, I hope I can have my server+password as a default (either in the config or using the query argument in a browser bookmark). I would not want to have to select the server manually each time I open CYP.

**Comment by ondras** [comment]
>  I assume you would put them in some JSON config file on the server and there should be no need for the browser to ever see the password at all. You could still just select the server via the "server" argument and CYP just matches that to the pairings and applies the password if there is one.

Exactly! Will try to do this.

**Comment by ondras** [comment]
Hi @emu42 ,

please try updating to the latest CYP and running `npm i` afterwards. Read more about the newly-available `passwords.json` feature at https://github.com/ondras/cyp#password-protected-mpd and let me know if that works for you.

**Comment by SirJson** [comment]
For what it's worth I would have had the same issue, but your passwords.json solution works well for me. Keep up the good work!

**Comment by ondras** [comment]
Great, so it looks like this feature is working.
