### ISSUE TITLE
Installation crashed because of ws2mpd

### ISSUE THREAD

**Issue by emiquey** [ondras/cyp#5]
Hi, 
I tried to install cyp following your instruction, but when executing `npm i`, it crashed with the following message:
```
npm WARN package.json 0@1.0.0 No repository field.
npm ERR! notarget No compatible version found: ws2mpd@'>=2.0.0 <3.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.14.98-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! cwd /home/pi/Bureau/cyp
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Bureau/cyp/npm-debug.log
npm ERR! not ok code 0
```
I attached the file npm-debug.log for detailed information.
[npm-debug.log](https://github.com/ondras/cyp/files/3245194/npm-debug.log)

I also tried to get ws2mpd from your git repo, I cloned it and made `npm i` in the repo which ran successfully, but even after that the installation of cyp still fails.

Do you have any idea on how to solve this issue?
Cheers,

Étienne

**Comment by ondras** [comment]
Hi Etienne,

I would guess that the problem is dependency on Node >= 10.x, for both `ws2mpd` and `cyp`. Even if you manage to somehow install these packages, they won't run (Node < 10 is missing the `off` synonym for `removeListener`).

Are you able to upgrade your Node version to 10+? If not, we might try to reduce the dependency, but keep in mind that Node 8 is currently only in *maintenance mode*.

**Comment by emiquey** [comment]
Indeed you were right, I installed the Node 10.x and the installation went through. Thanks!
